######################################################################
#
#  .____     .__   __           _________  .__               __
# |    |    |__|_/  |_   ____  \_   ___ \ |  |__  _____   _/  |_
# |    |    |  |\   __\_/ __ \ /    \  \/ |  |  \ \__  \  \   __\
# |    |___ |  | |  |  \  ___/ \     \____|   Y  \ / __ \_ |  |
# |_______ \|__| |__|   \___  > \______  /|___|  /(____  / |__|
#         \/                \/         \/      \/      \/
#
# 插件的常规性设置 Version 1.4+
#
######################################################################
GENERAL:
  # 调试模式
  DEBUG: false
  # 禁用此插件功能的世界
  DISABLED-WORLDS: [PUT_YOUR_WORLD_NAME_HERE, ANOTHER_WORLD]
  # 依赖的 PAPI 变量
  # 若安装 PAPI，将自动帮你下载填写到这里的变量拓展 (如果存在)
  DEPEND-EXPANSIONS:
    - 'player'
    - 'server'
    - 'vault'
    - 'multiverse'


# 聊天颜色代码相关设置
# 颜色代码权限节点: trchat.color.<CODE>
# 例如玩家拥有 trchat.color.a, 则可使用 &a 颜色代码
CHAT-COLOR:
  # 是否在常规聊天中启用颜色代码
  CHAT: true
  # 是否在木牌中启用颜色代码
  SIGN: true
  # 是否在铁砧中启用颜色代码
  ANVIL: true
  # 是否在编辑书时启用颜色代码
  BOOK: true

# 聊天控制管理
CHAT-CONTROL:
  # 每两次聊天需要等待的间隔时间
  COOLDOWN: 2.0
  # 聊天内容的字符限制
  LENGTH-LIMIT: 100